version: "3.8"

services:
  api:
    build: .
    container_name: quest-tracker-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - app-network
    command: >
      bash -c "if ls /app/alembic/versions/*.py 1> /dev/null 2>&1; then
                echo 'Migrations already exist.'
              else
                echo 'No migrations found. Creating initial migration...'
                alembic revision --autogenerate -m 'initial'
              fi &&
              echo 'Applying any pending migrations...' &&
              alembic upgrade head &&
              if [ \"\$SEED_DB\" = \"true\" ]; then
                echo 'Seeding data...'
                python scripts/seed_data.py
              else
                echo 'Skipping database seeding. Set SEED_DB=true to seed.'
              fi &&
              echo 'Starting API...' &&
              uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

networks:
  app-network:
    driver: bridge

