version: "3.8"

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG}
    restart: always
    ports:
      - "80:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - app_data:/data

volumes:
  app_data:
