services:
  app:
    image: ghcr.io/narzau/quest-logger:${IMAGE_TAG}
    restart: always
    ports:
      - "80:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - app_data:/data

volumes:
  app_data:
