"""Add completed_at to quests

Revision ID: 551963ce9889
Revises: e9f8e08bacfc
Create Date: 2025-03-01 07:54:51.853828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551963ce9889'
down_revision: Union[str, None] = 'e9f8e08bacfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'completed_at')
    # ### end Alembic commands ###