"""notes processing and tracking minutes

Revision ID: b4394fb711ac
Revises: df78e43471b9
Create Date: 2025-03-16 09:17:56.300993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4394fb711ac'
down_revision: Union[str, None] = 'df78e43471b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('minutes_tracked', sa.Float(), nullable=True))
    op.add_column('notes', sa.Column('minutes_refunded', sa.Boolean(), nullable=True))
    op.add_column('notes', sa.Column('processing_status', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('processing_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'processing_error')
    op.drop_column('notes', 'processing_status')
    op.drop_column('notes', 'minutes_refunded')
    op.drop_column('notes', 'minutes_tracked')
    # ### end Alembic commands ###