"""add google calendar integration

Revision ID: d16aa461da84
Revises: eef2df8bfc9b
Create Date: 2025-03-05 11:30:13.963203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16aa461da84'
down_revision: Union[str, None] = 'eef2df8bfc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('google_calendar_event_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_token_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('google_oauth_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_oauth_state')
    op.drop_column('users', 'google_token_expiry')
    op.drop_column('users', 'google_refresh_token')
    op.drop_column('users', 'google_token')
    op.drop_column('quests', 'google_calendar_event_id')
    # ### end Alembic commands ###