services:
  api:
    image: ghcr.io/narzau/quest-logger:${IMAGE_TAG}
    restart: unless-stopped
    networks:
      - backend
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}

networks:
  backend:
    external: true
