services:
  api:
    image: ghcr.io/narzau/quest-logger:${IMAGE_TAG}
    restart: unless-stopped
    networks:
      - backend
    environment:
      - UVICORN_PROXY_HEADERS=1
      - FORWARDED_ALLOW_IPS=*
    env_file:
      - ./.env

networks:
  backend:
    name: backend
    external: true
