services:
  app:
    image: ghcr.io/narzau/quest-logger:${IMAGE_TAG}
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "80:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    volumes:
      - app_data:/data

networks:
  backend:
    external: true
