services:
  api:
    image: ghcr.io/narzau/quest-logger:${IMAGE_TAG}
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - ./.env

networks:
  backend:
    name: backend
    external: true
