name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push with Kaniko
        uses: google-github-actions/build-push-kaniko@v2
        with:
          context: ${{ github.workspace }}
          dockerfile: ${{ github.workspace }}/Dockerfile
          destination: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}_${{ github.run_id }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}_latest
          cache: true
