name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push with Kaniko
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Execute Kaniko
        run: |
          docker run \
            --rm \
            -v ${{ github.workspace }}:/workspace \
            -v /var/run/docker.sock:/var/run/docker.sock \
            gcr.io/kaniko-project/executor:v1.9.0 \
            --context /workspace \
            --dockerfile /workspace/Dockerfile \
            --destination ghcr.io/${{ github.repository }}:${{ github.ref_name }}_${{ github.run_id }} \
            --destination ghcr.io/${{ github.repository }}:${{ github.ref_name }}_latest \
            --cache=true
