name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kaniko authentication
        run: |
          mkdir -p "${HOME}/.docker"
          echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64 | tr -d '\n')\"}}}" > "${HOME}/.docker/config.json"

      - name: Build and push with Kaniko
        uses: docker://gcr.io/kaniko-project/executor:v1.9.0
        env:
          DOCKER_CONFIG: "${HOME}/.docker" # Point to writable config location
        with:
          args: |
            --context=${{ github.workspace }}
            --dockerfile=${{ github.workspace }}/Dockerfile
            --destination=ghcr.io/${{ github.repository }}:${{ github.ref_name }}_${{ github.run_id }}
            --destination=ghcr.io/${{ github.repository }}:${{ github.ref_name }}_latest
            --cache=true
