name: Build and Push Docker Image

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:v1.9.0-debug
      options: --entrypoint=""
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push with Kaniko
        env:
          CI_REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
        run: |
          /kaniko/executor \
            --context "${{ github.workspace }}" \
            --dockerfile "${{ github.workspace }}/Dockerfile" \
            --destination "${CI_REGISTRY_IMAGE}:${{ github.ref_name }}_${{ github.run_id }}" \
            --destination "${CI_REGISTRY_IMAGE}:${{ github.ref_name }}_latest" \
            --cache=true
