name: Build and Push

on:
  push:
    branches: [main, production]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker auth
        run: |
          mkdir -p "${HOME}/.docker"
          echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64 | tr -d '\n')\"}}}" > "${HOME}/.docker/config.json"

      - name: Build and push
        uses: docker://gcr.io/kaniko-project/executor:v1.9.0
        with:
          args: >-
            --context=/github/workspace
            --dockerfile=/github/workspace/Dockerfile
            --destination=ghcr.io/${{ github.repository }}:${{ github.run_id }}
            --destination=ghcr.io/${{ github.repository }}:latest
            --cache=true
        env:
          DOCKER_CONFIG: "${HOME}/.docker"
