name: Build and Push

on:
  push:
    branches: [main, production]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure credentials
        run: |
          mkdir -p "${HOME}/.docker"
          CREDENTIALS=$(echo -n "github:${{ secrets.CR_PAT }}" | base64 -w 0)
          echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$CREDENTIALS\"}}}" > "${HOME}/.docker/config.json"
          echo "Docker config:"
          cat "${HOME}/.docker/config.json"

      - name: Build and push
        uses: docker://gcr.io/kaniko-project/executor:v1.12.0
        with:
          args: >-
            --context=/github/workspace
            --dockerfile=/github/workspace/Dockerfile
            --destination=ghcr.io/narzau/quest-logger:latest
            --cache=true
            --verbosity=debug
            --skip-tls-verify
        env:
          DOCKER_CONFIG: "${HOME}/.docker"
