name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push"]
    branches: [production, main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.ENVIRONMENT_IP }} >> ~/.ssh/known_hosts

      - name: Prepare deployment
        run: |
          # Get the successful build's run ID
          IMAGE_TAG=${{ github.event.workflow_run.id }}

          # Update compose file with actual image tag
          sed "s/\${IMAGE_TAG}/$IMAGE_TAG/" deployment/docker-compose/production.yml > docker-compose.yaml

          # Debug output
          echo "Using image tag: $IMAGE_TAG"
          echo "Generated compose file:"
          cat docker-compose.yaml

      - name: Deploy to Server
        run: |
          scp -P ${{ secrets.SSH_PORT }} docker-compose.yaml deployer@${{ secrets.ENVIRONMENT_IP }}:/home/deployer/app/
          ssh -p ${{ secrets.SSH_PORT }} deployer@${{ secrets.ENVIRONMENT_IP }} "
            cd /home/deployer/app
            docker compose down
            docker compose up -d
          "
