name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push"]
    branches: [production, main]
    types:
      - completed

jobs:
  deploy:
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.ENVIRONMENT_IP }}" > ~/.ssh/known_hosts

      - name: Prepare and deploy
        run: |
          # Get the actual image tag from build workflow
          IMAGE_TAG=${{ github.event.workflow_run.id }}

          # Generate compose file with debug output
          sed "s/\${IMAGE_TAG}/$IMAGE_TAG/" deployment/docker-compose/production.yml > docker-compose.yaml
          echo "=== GENERATED COMPOSE FILE ==="
          cat docker-compose.yaml

          # Copy compose file to server
          scp -P "${{ secrets.SSH_PORT }}" docker-compose.yaml deployer@"${{ secrets.ENVIRONMENT_IP }}":/home/deployer/app/

          # Execute deployment commands
          ssh -p "${{ secrets.SSH_PORT }}" deployer@"${{ secrets.ENVIRONMENT_IP }}" "
            cd /home/deployer/app
            echo '=== CURRENT CONTAINERS ==='
            docker ps -a
            echo '=== STOPPING EXISTING ==='
            docker compose down || true
            echo '=== STARTING NEW ==='
            docker compose up -d
            echo '=== UPDATED STATUS ==='
            docker ps
          "
