name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push"]
    branches: [production, main]
    types:
      - completed

jobs:
  deploy:
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.ENVIRONMENT_IP }}" > ~/.ssh/known_hosts

      - name: Prepare and deploy
        run: |
          IMAGE_TAG=${{ github.event.workflow_run.id }}

          # Create migration-aware compose file
          sed "s/\${IMAGE_TAG}/$IMAGE_TAG/" deployment/docker-compose.prod.yml > docker-compose.api.yml

          scp -P "${{ secrets.SSH_PORT }}" docker-compose.api.yml deployer@"${{ secrets.ENVIRONMENT_IP }}":/home/deployer/app/

          ssh -p "${{ secrets.SSH_PORT }}" deployer@"${{ secrets.ENVIRONMENT_IP }}" "
            cd /home/deployer/app
            
            # Pull new image first
            docker compose -f docker-compose.api.yml pull
            
            # Run migrations with new image
            docker compose -f docker-compose.api.yml run --rm api \
              alembic upgrade head
            
            # Rotate containers
            docker compose -f docker-compose.api.yml down
            docker compose -f docker-compose.api.yml up -d
          "
